### ISSUE TITLE
Page being hosted from README

### ISSUE THREAD

**Issue by R4356th** [Coders-school-c/Code-via-scratch#1]
Self-explanatory. The page is being hosted from our README, which has unnecessary dumb Jekkyl info. @Daniel4-Scratch, are you sure you want it this way?

**Comment by Spaceflyer234** [comment]
This is because the main file is called, "home.html". I think renaming in to, "index.html" will fix this issue.

**Comment by R4356th** [comment]
@Spaceflyer234, no, that is not the case. Look at home.html, it does not have any words in it, only pictures. Besides, a script.js file is mentioned in it, while in reality, there is not any.

**Comment by R4356th** [comment]
Also, remember to write "Resolves #1" to automatically close the issue your PR will fix.

**Comment by Daniel4-Scratch** [comment]
I am only started github calm down

**Comment by Daniel4-Scratch** [comment]
@R4356th Can you fix the hosting issue please I have given you access as amin

**Comment by R4356th** [comment]
Yeah, @Daniel4-Scratch.

**Comment by R4356th** [comment]
I have fixed this issue. You can now visit https://coders-school-c.github.io/Code-via-scratch/ to confirm.

**Comment by Daniel4-Scratch** [comment]
thanks
